### ISSUE TITLE
Support for multiple regions in one plugin call?

### ISSUE THREAD

**Issue by simonblake-mp** [buildkite-plugins/ecr-buildkite-plugin#110]
Heya

We push the same images to ECR repos in different regions, so we end up with buildkite config looking something like:

```
ecr_login_apse2: &ecr_login_apse2
  - ecr#$ECR_PLUGIN_VERSION:
      login: true
      region: ap-southeast-2
ecr_login_euw1: &ecr_login_euw1      
  - ecr#$ECR_PLUGIN_VERSION:
      login: true
      region: eu-west-1
ecr_login_usw1: &ecr_login_usw1      
  - ecr#$ECR_PLUGIN_VERSION:
      login: true
      region: us-west-1
ecr_login_usw2: &ecr_login_usw2      
  - ecr#$ECR_PLUGIN_VERSION:
      login: true
      region: us-west-2

steps:
  - label: ":docker: Build app image"
    plugins:
      - docker-compose#$DOCKER_COMPOSE_PLUGIN_VERSION:
          config: docker-compose.yml
          build: "${MAIN_SERVICE}"
          push:
            - "${MAIN_SERVICE}:${REPO_PREFIX}.ap-southeast-2.${REPO_SUFFIX}:${BUILD_TAG}"
            - "${MAIN_SERVICE}:${REPO_PREFIX}.eu-west-1.${REPO_SUFFIX}:${BUILD_TAG}"
            - "${MAIN_SERVICE}:${REPO_PREFIX}.us-east-1.${REPO_SUFFIX}:${BUILD_TAG}"
            - "${MAIN_SERVICE}:${REPO_PREFIX}.us-west-1.${REPO_SUFFIX}:${BUILD_TAG}"
            - "${MAIN_SERVICE}:${REPO_PREFIX}.us-west-2.${REPO_SUFFIX}:${BUILD_TAG}"
      - <<: *ecr_login_apse2
      - <<: *ecr_login_euw1
      - <<: *ecr_login_usw1
      - <<: *ecr_login_usw2     
```

It would be super nice if the region argument accepted a list - that would allow us to DRY up the config.  

And yes, I'm aware of ECR replication - sadly that has no particular performance guarantees, so when you've got steps further down the pipeline that depend on the image being available in a specific region, doing the push in the pipeline can be the easiest way to ensure it will be available when needed.  I can't imagine we're the only folks doing this  🙏
