### ISSUE TITLE
Doesn't play nice with `aws-assume-role`

### ISSUE THREAD

**Issue by orien** [buildkite-plugins/ecr-buildkite-plugin#33]
I see since [version 2.0.0](https://github.com/buildkite-plugins/ecr-buildkite-plugin/releases/tag/v2.0.0) this ECR plugin hooks into the step lifecycle at the `environment` stage. This breaks the integration with the `cultureamp/aws-assume-role` plugin.

To be specific we have _many_ build steps that follow this pattern:

```yml
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::$AWS_ACCOUNT_ID:role/$AWS_ROLE"
      - ecr#v1.2.0:
          login: true
          account_ids: "$AWS_ACCOUNT_ID"
      - docker-compose#v2.5.1:
          …
```

First the `aws-assume-role` plugin will assume a role that has access to the AWS ECR. Then the `ecr` plugin will log in and gain access to the ECR. Later the `docker-compose` plugin will pull and push to the ECR.

This pipeline fails when the `ecr` plugin is upgraded to version 2.0.0: the `docker-compose` plugin is refused access to the ECR. As the `ecr` plugin now runs at the `environment` phase it always runs before the `aws-assume-role` plugin, which runs at the `pre-command` phase, thus breaking the authorisation.

There's not much information shared in #26 to describe the reason or benefit in this change.

**Comment by lox** [comment]
Sorry this broke things for you @orien! The change in #26 was so that ECR could be used in the pre-command hook, which was a common request. 

Let's reach out to the folks at CultureAmp and see if we can get them to make the same change.

**Comment by migueleliasweb** [comment]
I have the exact same problem 😭 ....

**Comment by keithduncan** [comment]
From what I can tell this is fixed as of https://github.com/cultureamp/aws-assume-role-buildkite-plugin/pull/10

If anyone is still having issues don’t hesitate to comment and we’ll take a look!

**Comment by orien** [comment]
Unfortunately not, cultureamp/aws-assume-role-buildkite-plugin#10 was quickly reverted in cultureamp/aws-assume-role-buildkite-plugin#11. 😞 

However, we've been using a fork at [envato/aws-assume-role-buildkite-plugin](https://github.com/envato/aws-assume-role-buildkite-plugin). This has the proposed changes accepted and tagged. This works well for us:

```yaml
    plugins:
      - envato/aws-assume-role#v0.2.0-envato:
          role: "arn:aws:iam::$AWS_ACCOUNT_ID:role/$AWS_ROLE"
      - ecr#v2.3.0:
          login: true
          account_ids: "$AWS_ACCOUNT_ID"
      - docker-compose#v3.8.0:
          …
```
