### ISSUE TITLE
Unable to checkout version tags?

### ISSUE THREAD

**Issue by onlywei** [buildkite-plugins/ecr-buildkite-plugin#97]
Hello, apologies if this question is somewhat dumb as I am new to buildkite. I am trying to use this ecr plugin, and for some reason it is unable to git checkout any of the version tags. The error I am getting is as follows:

```
# Plugin "github.com/buildkite-plugins/ecr-buildkite-plugin" will be checked out to "/var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-ecr-buildkite-plugin-2-6-0"
--
# Switching to the temporary plugin directory
$ cd /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-ecr-buildkite-plugin-2-6-03887800207
$ git clone -v --recursive -- https://github.com/buildkite-plugins/ecr-buildkite-plugin .
Cloning into '.'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (gzip 1402 to 662 bytes)
remote: Enumerating objects: 653, done.
  | remote: Counting objects: 100% (99/99), done.
  | remote: Compressing objects: 100% (57/57), done.
  | remote: Total 653 (delta 43), reused 74 (delta 32), pack-reused 554
  | Receiving objects: 100% (653/653), 161.76 KiB \| 12.44 MiB/s, done.
  | Resolving deltas: 100% (296/296), done.:   0% (0/296)
# Checking out `2.6.0`
$ git checkout -f 2.6.0
error: pathspec '2.6.0' did not match any file(s) known to git
```

My buildkite steps are written as follows:

```
steps:
  - label: "build-and-push-ECR"
    command: "build_and_push.sh"
    plugins:
      - ecr#2.6.0:
          login: true
          account-ids:
            - "public.ecr.aws"
```

I've tried both `#2.6.0` and `#2.7.0`, but both fail to git checkout.

**Comment by pzeballos** [comment]
Hi @onlywei! sorry that it took us so long to respond 🙇🏻‍♀️ In case you didn't fix the issue (and for future travellers), when referring to the plugin by using only the name you need to specify the exact version name. So in this case (using the latest version) it will be:

```
steps:
  - label: "build-and-push-ECR"
    command: "build_and_push.sh"
    plugins:
      - ecr#v2.8.0:
          login: true
          account-ids:
            - "public.ecr.aws"
         
```

Note the `v` before the version number 🙂

Cheers,
